AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

# Metrics cops - be more lenient for test files and complex Redis operations
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    
Metrics/ClassLength:
  Max: 600 # Allow large storage and connection classes for Redis operations

Metrics/MethodLength:
  Max: 250 # Allow very long methods for Redis command implementations

Metrics/CyclomaticComplexity:
  Max: 75 # Allow very complex case statements for Redis commands

Metrics/PerceivedComplexity:
  Max: 75

Metrics/AbcSize:
  Max: 250 # Allow very high ABC size for Redis command parsing

# Naming cops
Naming/MethodParameterName:
  MinNameLength: 2 # Allow short Redis parameter names like ex, px

# Style cops
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

# Disable some cops that are overly strict for Redis command implementations
Style/NumericPredicate:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

# Allow unused method arguments for interface compatibility
Lint/UnusedMethodArgument:
  Enabled: false

# Allow duplicate branches for type checking
Lint/DuplicateBranch:
  Enabled: false

# Allow slicing with range for backwards compatibility
Style/SlicingWithRange:
  Enabled: false

# Allow safe navigation style preference
Style/SafeNavigation:
  Enabled: false

# Allow select with regex for clarity
Style/SelectByRegexp:
  Enabled: false

# Gemspec requirements
Gemspec/RequireMFA:
  Enabled: false
